### ISSUE TITLE
Fix React Redux Version

### ISSUE THREAD

**Issue by waynebrantley** [aspnet/JavaScriptServices#1059]
Consider fixing the redux version to 3.6 or updating to 3.7
On a fresh install 3.7 will be installed and that has breaking changes - your template will no longer compile

```
    ERROR in [at-loader] ./ClientApp/configureStore.ts:21:19
        TS2349: Cannot invoke an expression whose type lacks a call signature. T
ype '{}' has no compatible call signatures.
```

**Comment by SteveSandersonMS** [comment]
The redux version is fixed to 3.6.0 on current templates: https://github.com/aspnet/JavaScriptServices/blob/dev/templates/ReactReduxSpa/package.json#L34

Thanks for the advance warning about 3.7.0 though. When we update the pinned version to 3.7.0 we will of course have to fix the compilation error at the same time.

**Comment by cculver** [comment]
This appears to not be fixed. On starting a new project in .net core 2.0 (just released), redux is pinned to version 3.7.1. I am getting this same compilation error. Is there a fix in order?
