### ISSUE TITLE
HMR Not Working with aspnet-webpack-react 2.0.0

### ISSUE THREAD

**Issue by MapleYe** [aspnet/JavaScriptServices#1020]
After upgrading aspnet-webpack-react to 2.0.0 on ASP.NET core 1.1, I got error: 
Uncaught Error: Cannot find module "react-hot-loader/patch"

The package.json before update works well with aspnet-webpack-react 1.0.5:
`"aspnet-prerendering": "^2.0.3",
    "aspnet-webpack": "^1.0.28",
    "aspnet-webpack-react": "^1.0.5",
    "babel-loader": "^6.4.1",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-react-html-attrs": "^2.0.0",
    "babel-plugin-transform-class-properties": "^6.23.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-es2015": "^6.24.0",
    "babel-preset-react": "^6.23.0",
    "babel-preset-stage-0": "^6.22.0",
    "bootstrap": "^3.3.7",
    "css-loader": "^0.27.3",
    "expose-loader": "^0.7.3",
    "file-loader": "^0.10.1",
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-redux": "^5.0.3",
    "react-router": "^4.1.1",
    "react-router-dom": "^4.1.1",
    "react-thunk": "^1.0.0",
    "redux": "^3.6.0",
    "style-loader": "^0.15.0",
    "url-loader": "^0.5.8",
    "webpack": "^2.2.1",
    "webpack-hot-middleware": "^2.18.0",
    "webpack-merge": "^4.1.0",
    "xmlhttprequest": "^1.8.0"`

**Comment by SteveSandersonMS** [comment]
`aspnet-webpack-react` 2+ works with applications that use React HMR 3.

If your application uses React HMR 2, then you need to stay on `aspnet-webpack-react` 1.x.
