### ISSUE TITLE
Visual Studio Professional 2017 15.5.3 update broke HMR

### ISSUE THREAD

**Issue by djdu** [aspnet/JavaScriptServices#1477]
I'm stuck with the Visual Studio Professional 2017 15.5.3 update. HMR is not starting. It worked fine before I updated the visual studio.

`An unhandled exception occurred while processing the request. NodeInvocationException: Prerendering failed because of error: Error: Cannot find module "./selectors"`

`AspNetCore._Views_Home_Index_cshtml+<>c__DisplayClass16_0+<<ExecuteAsync>b__0>d.MoveNext() in Index.cshtml + <div id="react-app" asp-prerender-module="ClientApp/dist/main-server" asp-prerender-data=data>Loading...</div>`

Does anyone experiencing this issue? Please help. Thanks.

**Comment by peterdobson** [comment]
After upgrading to VS to 15.5.3 my HMR stopped working too, but after a VS restart, webpack rebuild and a Ctrl-F5 on the browser HMR started working again

**Comment by djdu** [comment]
I updated the Visual Studio to 15.5.4, still same issue. I did what peterdobson said, unfortunately didn't work for me!

**Comment by djdu** [comment]
Uninstall VS 2017 and reinstalled it, seems to be working...
